### ISSUE TITLE
Concurrent Modification Exception 

### ISSUE THREAD

**Issue by Pepich** [RedstonerServer/Modules#37]
People leaving will cause a Map to be changed while it's being iterated over

[Loop causing the issue](https://github.com/RedstonerServer/Modules/blob/master/src/main/java/com/redstoner/modules/teleport/Teleport.java#L464)
[And the corresponding code with the modification](https://github.com/RedstonerServer/Modules/blob/master/src/main/java/com/redstoner/modules/teleport/Teleport.java#L468)

**Comment by Minenash** [comment]
Fixed in [this commit](https://github.com/RedstonerServer/Modules/commit/857dfe32ca67cc0a41068ba4cbb0b69b060fb2f2).
